name: gwtune
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - matplotlib
  - numpy
  - ipykernel
  - pandas
  - pip
  - pymysql
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - tqdm
  - umap-learn
  - pip:
      - pot==0.9.4
      - optuna>=3.2.0
      - adjustText
      - sqlalchemy-utils==0.41.1
      - torch>=2.4.1
      - torchvision>=0.19.1
      - torchaudio>=2.4.1